apiVersion: skaffold/v1beta5
kind: Config
profiles:
  - name: provisioner--dev
    build:
      artifacts:
        - image: registry.gitlab.com/clusterplatform/clusterplatform/builder-utils
          context: packages/provisioner/packages/builder-utils
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/ipxe-manager
          context: packages/provisioner/packages/ipxe-manager
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/ipxe-worker
          context: packages/provisioner/packages/ipxe-worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/grub-manager
          context: packages/provisioner/packages/grub-manager
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/grub-worker
          context: packages/provisioner/packages/grub-worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/syslinux-manager
          context: packages/provisioner/packages/syslinux-manager
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/syslinux-worker
          context: packages/provisioner/packages/syslinux-worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/iso-manager
          context: packages/provisioner/packages/iso-manager
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/iso-worker
          context: packages/provisioner/packages/iso-worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/bootruntime
          context: packages/provisioner/packages/bootruntime
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/distributor-manager
          context: packages/provisioner/packages/distributor-manager
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/distributor-worker
          context: packages/provisioner/packages/distributor-worker
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/mainscripts
          context: packages/provisioner/packages/mainscripts
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/subscripts
          context: packages/provisioner/packages/subscripts
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/kickstarts
          context: packages/provisioner/packages/kickstarts
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/prebootscripts
          context: packages/provisioner/packages/prebootscripts
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/postbootscripts
          context: packages/provisioner/packages/postbootscripts
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/sshkeys
          context: packages/provisioner/packages/sshkeys
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
        - image: registry.gitlab.com/clusterplatform/clusterplatform/gateway
          context: packages/provisioner/packages/gateway
          docker:
            dockerfile: Dockerfile.dev
          sync:
            src/*.js: /opt/clusterplatform/app/src
    deploy:
      kubectl:
        manifests:
          - packages/provisioner/packages/verdaccio/stack.yaml
          - packages/provisioner/packages/nats/stack.yaml
          - packages/provisioner/packages/redis/stack.yaml
          - packages/provisioner/packages/postgres/stack.yaml
          - packages/provisioner/packages/minio/stack.yaml
          - packages/provisioner/packages/builder-utils/stack.yaml
          - packages/provisioner/packages/ipxe-manager/stack.yaml
          - packages/provisioner/packages/ipxe-worker/stack.yaml
          - packages/provisioner/packages/grub-manager/stack.yaml
          - packages/provisioner/packages/grub-worker/stack.yaml
          - packages/provisioner/packages/syslinux-manager/stack.yaml
          - packages/provisioner/packages/syslinux-worker/stack.yaml
          - packages/provisioner/packages/iso-manager/stack.yaml
          - packages/provisioner/packages/iso-worker/stack.yaml
          - packages/provisioner/packages/bootruntime/stack.yaml
          - packages/provisioner/packages/distributor-manager/stack.yaml
          - packages/provisioner/packages/distributor-worker/stack.yaml
          - packages/provisioner/packages/mainscripts/stack.yaml
          - packages/provisioner/packages/subscripts/stack.yaml
          - packages/provisioner/packages/kickstarts/stack.yaml
          - packages/provisioner/packages/prebootscripts/stack.yaml
          - packages/provisioner/packages/postbootscripts/stack.yaml
          - packages/provisioner/packages/sshkeys/stack.yaml
          - packages/provisioner/packages/gateway/stack.yaml
