apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:10.7.0
          resources:
            limits:
              memory: 250Mi
              cpu: 250m
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /bitnami
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
data:
  POSTGRESQL_PASSWORD: postgres-password
  POSTGRESQL_USERNAME: postgres-username
  POSTGRESQL_DATABASE: postgres-database
  POSTGRESQL_URI: postgres://postgres-username:postgres-password@postgres:5432/postgres-database
