apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2019-02-06T21-16-36Z
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 9000
          args:
            - server
            - /data
          envFrom:
            - configMapRef:
                name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-public
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - port: 9000
      nodePort: 30900
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
data:
  MINIO_ENDPOINT: minio
  MINIO_PORT: "9000"
  MINIO_REGION: us-east-1
  MINIO_BUCKET: ipxes
  MINIO_ACCESS_KEY: minio-access-key
  MINIO_SECRET_KEY: minio-secret-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-public
data:
  MINIO_ENDPOINT: "46.101.180.149"
  MINIO_PORT: "30900"
  MINIO_REGION: us-east-1
  MINIO_BUCKET: ipxes
  MINIO_ACCESS_KEY: minio-access-key
  MINIO_SECRET_KEY: minio-secret-key
