apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
    - image: registry.gitlab.com/clusterplatform/clusterplatform/builder-utils
      context: packages/builder-utils
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/ipxe-manager
      context: packages/ipxe-manager
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/ipxe-worker
      context: packages/ipxe-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/grub-manager
      context: packages/grub-manager
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/grub-worker
      context: packages/grub-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/syslinux-manager
      context: packages/syslinux-manager
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/syslinux-worker
      context: packages/syslinux-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/iso-manager
      context: packages/iso-manager
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/iso-worker
      context: packages/iso-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/bootruntime
      context: packages/bootruntime
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
    - image: registry.gitlab.com/clusterplatform/clusterplatform/gateway
      context: packages/gateway
      docker:
        dockerfile: Dockerfile.dev
      sync:
        "src/*.js": /opt/clusterplatform/app/src
deploy:
  kubectl:
    manifests:
      - packages/verdaccio/stack.yaml
      - packages/nats/stack.yaml
      - packages/redis/stack.yaml
      - packages/postgres/stack.yaml
      - packages/minio/stack.yaml
      - packages/builder-utils/stack.yaml
      - packages/ipxe-manager/stack.yaml
      - packages/ipxe-worker/stack.yaml
      - packages/grub-manager/stack.yaml
      - packages/grub-worker/stack.yaml
      - packages/syslinux-manager/stack.yaml
      - packages/syslinux-worker/stack.yaml
      - packages/iso-manager/stack.yaml
      - packages/iso-worker/stack.yaml
      - packages/bootruntime/stack.yaml
      - packages/gateway/stack.yaml
