apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
    - image: registry.gitlab.com/clusterplatform/clusterplatform/builder-utils
      context: packages/builder-utils
    - image: registry.gitlab.com/clusterplatform/clusterplatform/ipxe-manager
      context: packages/ipxe-manager
    - image: registry.gitlab.com/clusterplatform/clusterplatform/ipxe-worker
      context: packages/ipxe-worker
    - image: registry.gitlab.com/clusterplatform/clusterplatform/grub-manager
      context: packages/grub-manager
    - image: registry.gitlab.com/clusterplatform/clusterplatform/grub-worker
      context: packages/grub-worker
    - image: registry.gitlab.com/clusterplatform/clusterplatform/syslinux-manager
      context: packages/syslinux-manager
    - image: registry.gitlab.com/clusterplatform/clusterplatform/syslinux-worker
      context: packages/syslinux-worker
    - image: registry.gitlab.com/clusterplatform/clusterplatform/gateway
      context: packages/gateway
deploy:
  kubectl:
    manifests:
      - packages/nats/stack.yml
      - packages/redis/stack.yml
      - packages/postgres/stack.yml
      - packages/minio/stack.yml
      - packages/verdaccio/stack.yml
      - packages/builder-utils/stack.yml
      - packages/ipxe-manager/stack.yml
      - packages/ipxe-worker/stack.yml
      - packages/grub-manager/stack.yml
      - packages/grub-worker/stack.yml
      - packages/syslinux-manager/stack.yml
      - packages/syslinux-worker/stack.yml
      - packages/gateway/stack.yml
