apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:1.4.1
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
    - port: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats-public
spec:
  type: NodePort
  selector:
    app: nats
  ports:
    - port: 4222
      nodePort: 30002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats
data:
  TRANSPORTER: nats://nats:4222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-public
data:
  TRANSPORTER: nats://142.93.30.63:30002
