apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipxe-worker
spec:
  selector:
    matchLabels:
      app: ipxe-worker
  template:
    metadata:
      labels:
        app: ipxe-worker
    spec:
      containers:
        - name: ipxe-worker
          image: clusterplatform/ipxe-worker
          resources:
            limits:
              memory: 150Mi
              cpu: 150m
          envFrom:
            - configMapRef:
                name: nats
            - configMapRef:
                name: redis
