apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio
spec:
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      initContainers:
        - name: verdaccio-init
          image: busybox
          command:
            - sh
            - "-c"
            - chmod 777 -R  /verdaccio/storage
          volumeMounts:
            - name: verdaccio
              mountPath: /verdaccio/storage
      containers:
        - name: verdaccio
          image: verdaccio/verdaccio:3.11.4
          resources:
            limits:
              memory: 250Mi
              cpu: 250m
          ports:
            - containerPort: 4873
          volumeMounts:
            - name: verdaccio
              mountPath: /verdaccio/storage
      volumes:
        - name: verdaccio
          persistentVolumeClaim:
            claimName: verdaccio
---
apiVersion: v1
kind: Service
metadata:
  name: verdaccio
spec:
  selector:
    app: verdaccio
  ports:
    - port: 4873
---
apiVersion: v1
kind: Service
metadata:
  name: verdaccio-public
spec:
  type: NodePort
  selector:
    app: verdaccio
  ports:
    - port: 4873
      nodePort: 30004
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio
data:
  NPM_USER: verdaccio-user
  NPM_PASS: verdaccio-password
  NPM_EMAIL: verdaccio-user@example.com
  NPM_REGISTRY: http://verdaccio:4873
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-public
data:
  NPM_USER: verdaccio-user
  NPM_PASS: verdaccio-password
  NPM_EMAIL: verdaccio-user@example.com
  NPM_REGISTRY: http://68.183.74.65:30004
