apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootruntime
spec:
  selector:
    matchLabels:
      app: bootruntime
  template:
    metadata:
      labels:
        app: bootruntime
    spec:
      containers:
        - name: bootruntime
          image: registry.gitlab.com/clusterplatform/clusterplatform/bootruntime
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: nats
            - configMapRef:
                name: postgres
            - configMapRef:
                name: verdaccio
