apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshkeys
spec:
  selector:
    matchLabels:
      app: sshkeys
  template:
    metadata:
      labels:
        app: sshkeys
    spec:
      containers:
        - name: sshkeys
          image: registry.gitlab.com/clusterplatform/clusterplatform/sshkeys.dev
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: nats
            - configMapRef:
                name: postgres
            - configMapRef:
                name: verdaccio
