apiVersion: apps/v1
kind: Deployment
metadata:
  name: prebootscripts
spec:
  selector:
    matchLabels:
      app: prebootscripts
  template:
    metadata:
      labels:
        app: prebootscripts
    spec:
      containers:
        - name: prebootscripts
          image: registry.gitlab.com/clusterplatform/clusterplatform/prebootscripts
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: nats
            - configMapRef:
                name: postgres
            - configMapRef:
                name: verdaccio
