apiVersion: apps/v1
kind: Deployment
metadata:
  name: localnode-manager
spec:
  selector:
    matchLabels:
      app: localnode-manager
  template:
    metadata:
      labels:
        app: localnode-manager
    spec:
      containers:
        - name: localnode-manager
          image: registry.gitlab.com/clusterplatform/clusterplatform/localnode-manager.prod
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: nats
            - configMapRef:
                name: postgres
