apiVersion: apps/v1
kind: Deployment
metadata:
  name: uboot-manager
spec:
  selector:
    matchLabels:
      app: uboot-manager
  template:
    metadata:
      labels:
        app: uboot-manager
    spec:
      containers:
        - name: uboot-manager
          image: registry.gitlab.com/clusterplatform/clusterplatform/uboot-manager.dev
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: nats
            - configMapRef:
                name: redis
            - configMapRef:
                name: postgres
            - configMapRef:
                name: verdaccio
