apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.gitlab.com/clusterplatform/clusterplatform/gateway.prod
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: nats
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-public
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-public
spec:
  rules:
    - host: api.provisioner.sandbox.cloud.alphahorizon.io
      http:
        paths:
          - path: /
            backend:
              serviceName: gateway
              servicePort: 3000
